# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursers', '0007_auto_20180202_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_time',
            field=models.IntegerField(default=0, verbose_name='时长'),
        ),
    ]
