# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-07 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursers', '0008_video_learn_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否广告'),
        ),
    ]
